"""Query DukeOTR's conservative verified Roblox knowledge / fast-answer layer.

A successful answer is copied from a source-checked entry. A fallback only reports the existing
adaptive effort route; this CLI intentionally does not invoke Ollama, Builder, Reviewer, or Fixer.
"""

from __future__ import annotations

if __package__ in {None, ""}:
    import sys as _bootstrap_sys
    from pathlib import Path as _BootstrapPath

    _bootstrap_sys.path.insert(0, str(_BootstrapPath(__file__).resolve().parents[1]))

import argparse
import json
import os
import sys
import tempfile
from datetime import date
from pathlib import Path
from typing import Any

from scripts.lib.io_utils import read_json, write_json_atomic
from scripts.lib.request_routing import route_user_request
from scripts.lib.verified_knowledge_audit import assert_safe_output_path


def parser() -> argparse.ArgumentParser:
    value = argparse.ArgumentParser(
        description="Return a source-checked DukeOTR fast answer or route safely to adaptive Builder/Reviewer/Tester/Fixer work."
    )
    value.add_argument("--prompt", required=True, help="One user request; narrow definition/explanation requests may qualify for a fast answer")
    value.add_argument("--config", default="configs/verified_knowledge.json")
    value.add_argument("--effort-config", default=None, help="Override the adaptive fallback config declared by verified_knowledge.json")
    value.add_argument("--as-of", default=None, help="ISO audit date for deterministic freshness checks (default: today)")
    value.add_argument("--format", choices=("json", "markdown"), default="json")
    value.add_argument("--output", default=None, help="Optional output artifact; the held-out evaluation file is always refused")
    return value


def _as_of(value: str | None) -> date | None:
    if value is None:
        return None
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise ValueError("--as-of must use ISO YYYY-MM-DD format") from exc


def _markdown(result: dict[str, Any]) -> str:
    if result["route"] == "verified_knowledge_fast_answer":
        answer = result["fast_answer"]
        lines = [
            "# DukeOTR verified fast answer",
            "",
            f"**Concept:** {answer['canonical_name']} (`{answer['concept_id']}`)",
            f"**Depth:** {answer['depth']}",
            f"**Confidence:** {answer['confidence']}",
            "",
            answer["answer"],
            "",
            f"_Verification: {answer['last_verification']['verified_at']} · review by {answer['last_verification']['review_by']}_",
            "",
            "> This was rendered from a source-checked entry, not generated by a model. It remains outside training data.",
        ]
        return "\n".join(lines)
    fallback = result["fast_answer"]
    adaptive = result["adaptive_route"]
    lines = [
        "# DukeOTR adaptive pipeline required",
        "",
        f"**Verified-layer result:** `{fallback.get('reason', 'fallback')}`",
        f"**Adaptive effort:** `{adaptive['level']}`",
        f"**Reason(s):** {', '.join(adaptive['reasons'])}",
        "",
        "No canned answer was returned. Hand this request to the existing Builder → Reviewer/Tester → Fixer path.",
        "",
        "> This command did not invoke a model, read held-out prompt content into an answer, or promote anything to training data.",
    ]
    return "\n".join(lines)


def _write_text_atomic(path: str | Path, content: str) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=destination.parent, prefix=f".{destination.name}.", delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(content)
    os.replace(temporary, destination)


def main(argv: list[str] | None = None) -> int:
    arguments = parser().parse_args(argv)
    try:
        knowledge_config = read_json(arguments.config)
        if not isinstance(knowledge_config, dict):
            raise ValueError("Verified knowledge configuration must contain a JSON object")
        fallback = knowledge_config.get("adaptive_fallback", {})
        fallback_config = fallback.get("effort_config") if isinstance(fallback, dict) else None
        effort_config_path = arguments.effort_config or fallback_config
        if not isinstance(effort_config_path, str) or not effort_config_path:
            raise ValueError("Provide --effort-config or adaptive_fallback.effort_config in verified knowledge config")
        effort_config = read_json(effort_config_path)
        if not isinstance(effort_config, dict):
            raise ValueError("Adaptive effort configuration must contain a JSON object")
        evaluation_path = knowledge_config.get("evaluation_file")
        if not isinstance(evaluation_path, str) or not evaluation_path:
            raise ValueError("Verified knowledge config requires evaluation_file for overwrite protection")
        if arguments.output:
            assert_safe_output_path(arguments.output, evaluation_path)
        result = route_user_request(
            arguments.prompt,
            effort_config=effort_config,
            knowledge_config=knowledge_config,
            as_of=_as_of(arguments.as_of),
        )
        rendered = json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n" if arguments.format == "json" else _markdown(result) + "\n"
        if arguments.output:
            if arguments.format == "json":
                write_json_atomic(arguments.output, result)
            else:
                _write_text_atomic(arguments.output, rendered)
        else:
            print(rendered, end="")
        return 0
    except (FileNotFoundError, ValueError) as exc:
        print(f"Verified knowledge query failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
